### ISSUE TITLE
Using show {with_path = false} results is error

### ISSUE THREAD

**Issue by bikallem** [ocaml-ppx/ppx_deriving#149] opened 2017-09-09 17:31 UTC
I am attempting to use `show {with_path = false}` however, the compiler complains with the following error: 
`Error: non-optional labeled argument expected`

The following sample code fails in both toplevel and ocamlc.
`module X = struct type t = C [@@deriving show { with_path = false }] end;;`

**Comment by gasche** [comment] 2017-09-10 12:54
I am unable to reproduce it under `master` or `v4.2` under 4.05.0, and under 4.1 and 4.04 ppx-deriving complains that `show does not support option with_path`. What ppx-deriving and OCaml versions are your using?

**Comment by bikalgurung** [comment] 2017-09-10 16:36
I am using ocaml 4.05.0, jbuilder 1.0+beta13, and ppx_deriving 4.2

**Comment by copy** [comment] 2017-09-20 09:12
It's probably this issue with `ppx_type_conv`: https://github.com/janestreet/ppx_type_conv/issues/9

**Comment by bikalgurung** [comment] 2017-10-28 20:27
@copy Indeed, this issue seems related to `ppx_type_conv` and/or `ppx_driver`. I was using `ppx_hash` and `ppx_compare` along with `ppx_deriving` and I faced this issue. I removed the both `ppx_hash` and `ppx_driver` from jbuilder rules and `with_path` seem to work correctly.

**Comment by copy** [comment] 2017-12-05 20:45
The fixed version of `ppx_type_conv` has been released in opam, so this issue can be closed now.

**Closed** 2017-12-06 04:07 UTC
